# Generated by Django 3.2.7 on 2022-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_studyimages_color_studyimages_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyimages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studyimages',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
