# Generated by Django 3.2.7 on 2022-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220927_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyimages',
            name='date',
        ),
        migrations.RemoveField(
            model_name='studyimages',
            name='title',
        ),
        migrations.AddField(
            model_name='study',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
